services:
  artemis:
    image: apache/activemq-artemis:latest
    ports:
      - "5672:5672"
      - "8161:8161"
      - "61616:61616"
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
      ANONYMOUS_LOGIN: true

